### ISSUE TITLE
Load Ozone Data

### ISSUE THREAD

**Issue by rayi113** [ResearchSoftwareInstitute/greendatatranslator#10]
- 100 percent complete

**Comment by cpschmitt** [comment]
This issue is for loading ozone data to allow for getting raw ozone measurements through the exposure API.

**Comment by lstillwe** [comment]
James has script to do this - will share with Lisa

**Comment by lstillwe** [comment]
James delivered scripts, and I have modified to retrieve pm25 or o3 data and save all retrieved fields to DB loadable CSV file
