### ISSUE TITLE
Green Team Milestones and Budget, Months 19 to 27

### ISSUE THREAD

**Issue by karafecho** [ResearchSoftwareInstitute/greendatatranslator#106]
Steve, Kara, Kira and Asia are preparing milestones and a new budget request for the final term of the two-year feasibility study, May 2018 through January 2019, for subsequent discussion by the broader team.

**Comment by stevencox** [comment]
Budget planning and milestones document under development. Next meeting Wed. AM.

**Comment by karafecho** [comment]
Steve, Kara, and Margie met on Friday, 2/23 to develop a plan for finalizing budget/milestones. Still waiting on forms from Christine.

**Comment by karafecho** [comment]
Submitted budget/milestones on 03/29/2018.
