### ISSUE TITLE
Clinical Feature Vectors (aka, Clinical Co-occurrence Tables)

### ISSUE THREAD

**Issue by karafecho** [ResearchSoftwareInstitute/greendatatranslator#108]
Green Team is exploring the use of patient feature vectors (aka, clinical co-occurrence tables) to answer CQs  via Translator services. The hope is that the data are rich enough to answer certain types of CQs in a manner that is regulatory compliant and free of IRB concerns.  If successful, this approach will allow full execution of CQ1, CQ4, and CQ5.

**Comment by karafecho** [comment]
CMAQ output for 2010 and 2011 can be found here: https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/20

**Comment by karafecho** [comment]
**Approach 1:**

‘Study’ periods: 1/1/2010 - 12/31/2010 (‘study 1’) and 1/1/2011 - 12/31/2011 (‘study 2’) (two years for which exposures data are available)

Age at ‘study’ start date: calculated from birth date and binned as 0...2, 3...17, 18...34, 35...50, 51...69, 70+ years

Asthma-like phenotype: Default per patient pull criteria (ICD codes for asthma-like conditions)

Exposure to particulate matter: average exposure over ‘study’ period, binned as quintiles

Exposure to ozone: same as for particulate matter

Responsiveness to treatment: #ED/inpatient visits for respiratory issue(s) (defined by same ICD codes used to pull patients with an asthma-like phenotype) over ‘study’ period

Select asthma-related meds administered/prescribed over 'study' period (0 = not administered/prescribed; 1 = administered/prescribed at least one time) (see list of relevant meds below)

Additional variables of interest for state-trait stratification: Obesity: Obesity ICD code OR BMI >= 30 over ‘study’ period; Sex; Race; Ethnicity

**Patient feature vector, one for year 2010 and one for year 2011:** V(patient, time) = f(Sex, Race, Obesity, Age at study start date, #ED/inpatient visits for respiratory issue, year avg PM2.5 exposure, year avg ozone exposure, meds administered/prescribed over study period)

7 column headers!

**Approach 2:**

‘Study’ period: 1/1/2010 - 12/31/2010 (‘study 1’) and 1/1/2011 - 12/31/2011 (‘study 2’) (two years for which exposures data are available)

Age at ‘study’ start date: calculated from birth date and binned as 0...2, 3...17, 18...34, 35...50, 51...69, 70+ years

Asthma-like phenotype: Default per patient pull criteria (ICD codes for asthma-like conditions)

Exposure to particulate matter: maximum one-hour exposure over 24-hour period before ED/inpatient visit(s) for respiratory issue(s), binned as quintiles

Exposure to ozone: same as for particulate matter

Responsiveness to treatment: ED/inpatient visits for respiratory issue(s) (defined by same ICD codes used to pull patients with an asthma-like phenotype) and outpatient visits over ‘study’ period

Additional variables of interest for state-trait stratification: Obesity: Obesity ICD code OR BMI >= 30 over ‘study’ period; Sex; Race, Ethnicity

**Visit feature vector, one for year 2010 and one for year 2011:** V(visit, time) = f(Visit type, Sex, Race, Ethnicity, Obesity, Age at visit, 24 h PM2.5 exposure, 24 h ozone exposure)

6 column headers!

**Medications prescribed to patients with asthma-like phenotype:**

prednisone
fluticasone
mometasone
budesonide
beclomethasone
ciclesonide
flunisolide
albuterol
metaproterenol
diphenhydramine
fexofenadine
cetirizine
ipratropium
salmeterol
arformoterol
formoterol
indacaterol
theophylline
omalizumab
mepolizumab

**Comment by stevencox** [comment]
Described this approach to NCATS during Reasoner demo.

**Comment by empfff** [comment]
Clinical data piece done... handed off to @jameschump for linkage to environmental data. James and I will go over the final vectors before we provision to Gamma team.

**Comment by karafecho** [comment]
Architecture/approach to be presented to the CDWH Oversight Committee for approval to move forward with action plan.

**Comment by karafecho** [comment]
#122

**Comment by karafecho** [comment]
@stevencox : can we close this issue and leave #122? They seem a bit redundant.

**Comment by stevencox** [comment]
Sounds good.
