### ISSUE TITLE
Prototype the Orange Biocluster API

### ISSUE THREAD

**Issue by stevencox** [ResearchSoftwareInstitute/greendatatranslator#110]
Develop a prototype biocluster API using smartBag. 
Review with Marcin of Orange team to assess viability of the approach.

See this issue:
https://github.com/NCATS-Tangerine/smartBag/issues/2

**Comment by tubafrenzy** [comment]
Currently getting my feet wet with smartBag and am working on the prototype using the first 20 rows that Marcin emailed us.

**Comment by tubafrenzy** [comment]
Made a first pass at what the bicluster JSON-LD file might look like in order to best represent the sample data that Marcin emailed us. So now I am tweaking the example smart bag script to turn this JSON-LD + sample data into a queryable API.

**Comment by tubafrenzy** [comment]
This is mostly complete, there is a separate smartBag/example/bicluster directory that has everything necessary to turn the CSV file into a bicluster API. Steve helped me get the bicluster app deployed on Mesos, so now we just need to configure the DNS + nginx to expose it over HTTP.

**Comment by stevencox** [comment]
Prototype endpoint [here](https://bicluster.renci.org/apidocs/#/default)
Discussion with Orange about next steps ongoing.
Future work will be tracked beyond this prototype issue.
