### ISSUE TITLE
Green Team - KFBS Collaboration

### ISSUE THREAD

**Issue by karafecho** [ResearchSoftwareInstitute/greendatatranslator#116]
This issue regards a collaboration with Stephen Appold and Jim Johnson (KFBS) and Ann Moss Joyner and Allan Parnell (Cedar Grove Institute for Sustainable Communities, KFBS) that aims to develop a project plan for a new Green Team Socioenvironmental Service. The service would provide access to data derived from the US Census (ACS) for integration with patient data and provisioning via clinical feature vectors.

**Comment by stevencox** [comment]
We've moved the design of the clinical aggregate service along. We're brainstorming the approach [here](https://docs.google.com/presentation/d/1WWNCLmNQt2bEUO3N8cPmd910wQer0MhFFKDgDRDuSi0/edit#slide=id.p3). @lstillwe and @karafecho will take point on integration of this data.

**Comment by stevencox** [comment]
Next steps are, I believe,
  * Formalize the collaboration via the 2018 Translator funding process. 
  * Define KFBS/CGI specific competency questions
  * Do technical design and implementation of clinical feature vector work
@karafecho - please edit as appropriate.
