### ISSUE TITLE
CMAQ Exposures API: quality metrics retrieval flag - default to false

### ISSUE THREAD

**Issue by lstillwe** [ResearchSoftwareInstitute/greendatatranslator#125]
RENCI/cmaq-exposure-api#19

**Comment by lstillwe** [comment]
90% complete - just need to redeploy

**Comment by karafecho** [comment]
#123

**Comment by lstillwe** [comment]
Still need to redeploy - will try and finish up this week.

**Comment by lstillwe** [comment]
Changes redeployed to bdtshare.renci.org. This issue is now finished.

**Comment by stevencox** [comment]
@lstillwe, what's the public URL for this service?

**Comment by lstillwe** [comment]
http://bdtshare.renci.org:5000/v1/ui/#/
