### ISSUE TITLE
Create Exposures API Architecture Diagram

### ISSUE THREAD

**Issue by stevencox** [ResearchSoftwareInstitute/greendatatranslator#139]
Create an architecture diagram describing the data ingest process, database architecture, and web service architecture for the exposures API. Include new APIs for roadway and socioenvironmental data.

**Comment by stevencox** [comment]
Hi Lisa - do we have something readily available on this or should we meet to whiteboard a diagram?

**Comment by lstillwe** [comment]
Hi Steve,

There is some info in the GitHub repo - but not a real architecture diagram.
Sure we can whiteboard it. I had started some notes already - not sure how detailed you what to get -  i.e. listings of tables and all fields, indexes, etc.

Lisa

On Jun 20, 2018, at 4:21 PM, Steven <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lisa - do we have something readily available on this or should we meet to whiteboard a diagram?

**Comment by stevencox** [comment]
Perhaps we could start with a slide deck in the [Green Team architecture folder](https://drive.google.com/drive/folders/1X5UWhKmzSxwnGkDdCBNadWzLCR9eEfWU). I'm looking for something that shoes the main components (CMAQ API, Exposures API, SocioAPI, ROWAPI), etc. Could you take a first pass at it and we can iterate a bit?

**Comment by lstillwe** [comment]
Documentation for the Data Translator APIs is complete and available here: https://github.com/lstillwe/datatranslator-exposure-apis
