### ISSUE TITLE
Develop CMAQ Environmental Exposures API and UI

### ISSUE THREAD

**Issue by karafecho** [ResearchSoftwareInstitute/greendatatranslator#141]
The purpose of this issue is to develop a second API and related UI to exposure nationwide CMAQ estimates, one PM2.5 and O3 measure per day per year (2002-2014) per US Census tract centroid.

**Comment by lstillwe** [comment]
Not sure time will permit the implementation of this API for the September timeframe at 20% effort level. Will make this the last priority.

**Comment by arunacs** [comment]
New CMAQ data for 2011 in the new format are now available at:
/proj/ie/proj/NIH-DataTranslator/for_RENCI/CMAQ/FAQSD/2011/
2011_pm25_daily_average.txt
2011_ozone_daily_8hour_maximum.txt

**Comment by arunacs** [comment]
Additional years of CMAQ data in same format as above available now:
/proj/ie/proj/NIH-DataTranslator/for_RENCI/CMAQ/FAQSD/

2014:
2014_ozone_daily_8hour_maximum.txt.gz
2014_pm25_daily_average.txt.gz

2013:
2013_pm25_daily_average.txt.gz
2013_ozone_daily_8hour_maximum.txt.gz

2012:
2012_ozone_daily_8hour_maximum.txt.gz
2012_pm25_daily_average.txt.gz

2011:
2011_pm25_daily_average.txt.gz
2011_ozone_daily_8hour_maximum.txt.gz

2010:
2010_pm25_daily_average.txt.gz
2010_ozone_daily_8hour_maximum.txt.gz

**Comment by karafecho** [comment]
From Lisa: The new expanded CMAQ API is completed and now available here:http://bdt-cmaq.renci.org:8080/cmaq_exposures_api/v1/swagger.json
Also please see this repository for documentation: https://github.com/lstillwe/datatranslator-exposure-apis

**Comment by arunacs** [comment]
8 more years of CMAQ data available:

/proj/ie/proj/NIH-DataTranslator/for_RENCI/CMAQ/FAQSD

2009:
2009_pm25_daily_average.txt.gz
2009_ozone_daily_8hour_maximum.txt.gz

2008:
2008_pm25_daily_average.txt.gz
2008_ozone_daily_8hour_maximum.txt.gz

2007:
2007_pm25_daily_average.txt.gz
2007_ozone_daily_8hour_maximum.txt.gz

2006:
2006_pm25_daily_average.txt.gz
2006_ozone_daily_8hour_maximum.txt.gz

2005:
2005_pm25_daily_average.txt.gz
2005_ozone_daily_8hour_maximum.txt.gz

2004:
2004_pm25_daily_average.txt.gz
2004_ozone_daily_8hour_maximum.txt.gz

2003:
2003_pm25_daily_average.txt.gz
2003_ozone_daily_8hour_maximum.txt.gz

2002:
2002_pm25_daily_average.txt.gz
2002_ozone_daily_8hour_maximum.txt.gz
