### ISSUE TITLE
Modularize Onto

### ISSUE THREAD

**Issue by stevencox** [ResearchSoftwareInstitute/greendatatranslator#148]
Move the Onto service from [robokop](https://github.com/NCATS-Gamma/robokop-interfaces) to a new repository in the [Tangerine](https://github.com/NCATS-Tangerine).

Add
  * [x] Unit tests.
  * [x] Automated build, including Docker container.

**Comment by stevencox** [comment]
See the existing [code](https://github.com/NCATS-Gamma/robokop-interfaces/blob/master/greent/services/ontology.py) and [tests](https://github.com/NCATS-Gamma/robokop-interfaces/blob/master/greent/test/test_ontology.py) for ontology logic.

In a local development environment, port the ontology [api](https://github.com/NCATS-Gamma/robokop-interfaces/blob/master/greent/api/onto.py) and supporting components out of the robokop-interfaces repo. Add the tests above and integrate.

**Comment by stevencox** [comment]
Created a greentranslator dockerhub account.
Also created a GitHub [repo](https://github.com/NCATS-Tangerine/reasoner-tools) for this work.

**Comment by ColinKCurtis** [comment]
- Added method "id_list" to ontology.py

- onto.py, ontology.py, and associated files/tests added to new repo at [NCATS-Tangerine / reasoner-tools](https://github.com/NCATS-Tangerine/reasoner-tools/tree/master/greent)

- using [green-compose toolkit](https://github.com/NCATS-Tangerine/green-compose), Docker build and push executed ... 'onto' service container now living at [greentranslator Dockerhub](https://hub.docker.com/u/greentranslator/)

- this updated 'onto' service is now an instantiated application through Marathon/Mesos and is accessible/usable at https://onto.renci.org/apidocs/ ('onto' replaced 'onto2' application as the public-facing service. 'onto2' is still running, per Marathon, just in case)

- next modularization task is Bionames/naming ...

- please let me know of any concerns with the 'onto' service updates
