### ISSUE TITLE
Execute chemical/medical portions of green team queries

### ISSUE THREAD

**Issue by cpschmitt** [ResearchSoftwareInstitute/greendatatranslator#15]
- 10 percent complete

Document "GreenTeamQueryBiopsy_SixMonthPlan_v4_02.14.17.docx" holds the initial 6 month queries.  These queries contain subqueries that are clinical, environmental, chemical, medicinal, and biological in nature. This issue is to implement the medicinal/chemical portions of those queries. 

The priority of data sources to consider (in order) are:
- Monarch swagger-based api (http://api.monarchinitiative.org/api/)
- Monarch blaze graph implementation at RENCI
- chem2bio2rdf

Execution is ideally python running within zeppelin notebook, but can initially be a sparql query if that is easier to begin with.

Specific subqueries (start with 1-3 as 4-6 need more discussion)
1) - get list of medications for asthma 
2) - get list of targets (asthma targets) for a list of asthma medications
3) - get list of biological pathways for a list of asthma targets
4) - get list of initiating mechanisms (asthma IM) for PM2.5 and ozone
5) - get list of targets affected by asthma IMs and whether the interaction is activation or inhibition
6) - get list genes associated with up and down regulation of targets from 5

**Comment by stevencox** [comment]
See this [discussion](https://mesostars.wordpress.com/2017/02/19/interactive-analytics/) of RENCI's Zeppelin environment for status.

**Comment by stevencox** [comment]
Explored Monarch Initiative smartAPIs, WikiPathways and CHEMBL SPARQL endpoints as sources of data for the third query.

Loaded chem2bio2rdf kegg, reactome, and sider data networks into our graph database.

**Comment by karafecho** [comment]
High-level queries to Technical Approach doc can be found here: Dropbox/DataTranslatorProject/PostAwardDocs/Queries/GreenTeamQueriesToTechnicalApproach

**Comment by stevencox** [comment]
The chemical/medical data store was completed and is used in the Gamma reasoner.
