### ISSUE TITLE
Standup development server for clinical and environmental data environments

### ISSUE THREAD

**Issue by jameschump** [ResearchSoftwareInstitute/greendatatranslator#16]
- 100 percent complete

**Comment by KCB13** [comment]
Had a convo with @karafecho and she pointed out that development servers have been put in place at both RENCI (RENCI Translator GIS for socioenvironmental data and RENCI Translator RDF for bio/chem/med data) and NC TraCS (NC TraCS Translator i2b2 for real-world and Hush+ patient data). The plan is to transfer the RENCI systems/data to NC TraCS after development is complete. So, in some sense, this issue should be broken into several issues, in terms of development and transfer, with some carry over from 0-6 months to 6-12 months.

**Comment by KCB13** [comment]
Updated to 100% complete to match with [GreenTeamMilestonesTasksCommunications_0to6Months_03.02.17](https://docs.google.com/spreadsheets/d/1IG1PrzneSUBFFMZV4hlxREY0hQM7cODgt4fj5aYAl3o/edit#gid=1731054240) and moved to **Completed Issues**
