### ISSUE TITLE
Expanding BiCluster API with 'aggregation of row data'

### ISSUE THREAD

**Issue by colinkcurtis** [ResearchSoftwareInstitute/greendatatranslator#161]
Working with Marcin Joachimiak to expand the functionality at https://bicluster.renci.org/apidocs/

Currently in discussion mode on Slack.

**Comment by colinkcurtis** [comment]
We've set out a plan for, and coded the first working portion of, a "gene/tissue co-occurrence" processor which utilizes bicluster API, FA_1_core_complex, and FA_4_all_genes files

**Comment by karafecho** [comment]
@ColinKCurtis @stevencox  : Please keep Green Team posted on this. Marcin J. joined last Friday's mini-hackathon on WF5 and is anxious to get involved with our efforts.

**Comment by colinkcurtis** [comment]
- Marcin J. is now in touch with Steve Cox and Chris Bizon. 

- There is a repository of notebooks, found here: [Workflow 9 - Bicluster Notebooks](https://github.com/ncats/translator-workflows/tree/master/WorkFlow9) Within these notebooks, currently the "gene_to_gene..." and "tissue_to_tissue..." are in good condition for evaluation. The other two, "gene_to_tissue..." and "tissue_to_gene...", will require some code work in "biclusterco.py" to behave properly.
