### ISSUE TITLE
ICEES Facade

### ISSUE THREAD

**Issue by stevencox** [ResearchSoftwareInstitute/greendatatranslator#168]
1. Bring the operation implementation currently in this [service](https://github.com/NCATS-Tangerine/ros/blob/master/ros/wf5/ks_apis/icees/server.py) into alignment with current thinking on workflow five. (verify use of estimated population density, inequality values, p_value threshold, etc).

2. Verify all changes to that service continue to work with the workflow [here](https://github.com/NCATS-Tangerine/ros/tree/master/ros/wf5). 

3. Update the workflow name to something more readable.

4. Create a second endpoint using ed visits as a clustering criteria.

**Comment by colinkcurtis** [comment]
1. Checked with Kara and Hao.... currently, "urban" is defined as "EstResidentialDensity >= 3". This may change, they are going to confer with Steve Appold on this issue.

2. The changes did not break the system.

3. Changed the workflow pair (.cwl and .yml) to 'workflow_5_v_3.cwl' and 'workflow_5_v_3.yml' respectively. Still stands to be improved...

4. I've created a second endpoint which utilizes 'TotalEDInpatientVisits > 2' as the feature variable. This is done in the 'server.py' file... however, I delineated this into two new files which are now titled 'icees_res_density_server.py' and 'icees_ed_visits_server.py' to represent this bifurcation. These two files must be operated in the same way which server.py has been prior to now. 

The changes described in # 4 above, do not produce any change in the workflow output SIZE. In both cases, the output size is:
        "size": 883424,

Further, the checksum changes from test to test, even when nothing is changed and the original command is merely re-run. Current best guess is that there is a hard-limit to the size of the output but the gathering of contents is non-deterministic such that once ANY set of data of size = 883424, it is returned.

**Comment by stevencox** [comment]
Thanks - 

  * 1. sounds good.
  * 2. sounds good. (see 4 for caveat)
  * 3. sounds good.
  * 4. Please put both operations in a single server.py. We don't want to have to run separate services for each operation. This will mean each operation will have a different URL. That URL needs to be reflected in the CWL parameters for the workflow. Are we doing that somehow?

**Comment by colinkcurtis** [comment]
All issues addressed and the next set of concerns is addressed by issue #169
