### ISSUE TITLE
Export patient data from CDWH i2b2 schema and import to development environment

### ISSUE THREAD

**Issue by jameschump** [ResearchSoftwareInstitute/greendatatranslator#17]
- 100 percent complete

**Comment by KCB13** [comment]
Updated to 80% complete to match with [GreenTeamMilestonesTasksCommunications_0to6Months_03.02.17](https://docs.google.com/spreadsheets/d/1IG1PrzneSUBFFMZV4hlxREY0hQM7cODgt4fj5aYAl3o/edit#gid=1731054240)
