### ISSUE TITLE
Deploy Automated Tests

### ISSUE THREAD

**Issue by stevencox** [ResearchSoftwareInstitute/greendatatranslator#181]
Deploy automated tests using the [Translator Testing Framework](https://github.com/NCATS-Tangerine/translator-testing-framework) for [TranQL](https://github.com/NCATS-Tangerine/tranql) at our [Jenkins](https://stars-app.renci.org/jenkins/login?from=%2Fjenkins%2FpluginManager%2Favailable) instance.

**Comment by cnbennett3** [comment]
TranQL automated tests are up and running on Jenkins using the behave Translator Testing Framework.  Tests include availability tests and tests for correctness for both ROBOKOP and ICEES.
