### ISSUE TITLE
Stub Environmental Exposure API

### ISSUE THREAD

**Issue by rayi113** [ResearchSoftwareInstitute/greendatatranslator#19]
- 50 percent complete

**Comment by balhoff** [comment]
@mjstealey can you let me know if this issue is redundant with what you've done on your service implementation?

**Comment by mjstealey** [comment]
> can you let me know if this issue is redundant with what you've done on your service implementation

@balhoff - comes down to how you decide to define [Develop Exposure API Service](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/6). 

We read it as:
**define spec --> implement spec --> return stub data --> return real data**

So if you see any of those steps as a duplicate of this issue, then yes, we should make this issue go away.

We (@mjstealey, @lstillwe) should probably pow-wow with you a bit on what's been done thus far and get your feedback regarding where you think we should go. This is something we can do over WebEx if you'd like.

**Comment by KCB13** [comment]
Closed; refer to issue #6
