### ISSUE TITLE
Develop Clinical Query Service for HuSH+ Patient Data

### ISSUE THREAD

**Issue by rayi113** [ResearchSoftwareInstitute/greendatatranslator#21]
- 100 percent completed

**Comment by KCB13** [comment]
Updated to 100% complete to match with [GreenTeamMilestonesTasksCommunications_0to6Months_03.02.17](https://docs.google.com/spreadsheets/d/1IG1PrzneSUBFFMZV4hlxREY0hQM7cODgt4fj5aYAl3o/edit#gid=1731054240) and moved to **Completed Issues**

**Comment by rayi113** [comment]
Test of trel/irods#3576
