### ISSUE TITLE
Produce Exposure Data from RLINE

### ISSUE THREAD

**Issue by arunacs** [ResearchSoftwareInstitute/greendatatranslator#25]
- 10 % complete

**Comment by arunacs** [comment]
10% complete

Completed test run for 2011 for few census block centroids in Durham, Orange and Wake counties

**Comment by arunacs** [comment]
Comparing RLINE vs CMAQ-based primary PM2.5 due to onroad sources

**Comment by arunacs** [comment]
Had a good discussion with ITS re computing resource to be used for this part of the project, and it was decided that we will do this work on the Longleaf cluster. Waiting for virtual node set-up from ITS, and will then transition work to the more secure environment that Longleaf provides

**Comment by arunacs** [comment]
Migrated code/scripts to be run natively from Longleaf cluster, and performed test run. Still waiting on Virtual node set-up from ITS.

**Comment by arunacs** [comment]
Researched into PM components that MOVES puts out, to facilitate comparisons of Primary PM2.5 from RLINE vs. CMAQ

**Comment by arunacs** [comment]
Incoming FTP options supported by UNC:

https://help.unc.edu/help/using-its-research-computings-secure-ftp-server/

@jameschump, FYI

**Comment by KCB13** [comment]
Refer to issues #67 and #68

**Comment by arunacs** [comment]
Completed R-LINE modeling to generate hourly concentrations for all geocodes in the 3-county region of the Triangle, for the year 2011.  Generating summary statistics for QA, and will then upload or provide location on Longleaf

**Comment by arunacs** [comment]
Files location on Longleaf sent to Emily
