### ISSUE TITLE
Hackathon Tech Environment Prep

### ISSUE THREAD

**Issue by stevencox** [ResearchSoftwareInstitute/greendatatranslator#27]
- 90 % Complete Overall.  
Prepare for the **Hackathon**. 

Making progress towards these aims: 
* Consolidated **data model** of our heterogeneous sources: [55%]
  * Clinical
  * Environmental
  * Medical-BioChemical
* Preparing working **(alpha) data services** in each of the above areas [65%]
  * **Data Lake**: Get useful data - see sources detailed in the comments below.
* Getting infrastructure in place to work with the data [70%]
  * **API**: Python or other API to abstract interactions with Green data.
  * **Spark/Mesos/Blazegraph**: Have compute resources
  * **Devops**: Automate configuration of cluster resources
  * **Cloud**: Integrate with Translator (AWS) cloud
  * **Zeppelin**: notebook environment
  * **Visualization**: Lightning and Bokeh
  * **CI/CD**: Continuous integration and deployment
  * **NLP**: Investigate applicability of Quepy to query parsing, at least for SPARQL

**Comment by stevencox** [comment]
Weed ending March 17th:
* Fixed connectivity of Zeppelin to Apache Spark enabling more scalable analytics.
* Installed Lightning and Bokeh with Visualization demonstrations.
* Installed SKlearn library.
* Investigating alternate ways of deploying Exposure API to fix deployment issues.

**Comment by stevencox** [comment]
We should now have these data sources in our Blazegraph instance:
```
chem2bio2rdf/omim.n3
chem2bio2rdf/drugbank.n3
chem2bio2rdf/pubchem.n3
chem2bio2rdf/dcdb.n3
chem2bio2rdf/sider.n3
chem2bio2rdf/pharmgkb.n3
chem2bio2rdf/ctd.n3
chem2bio2rdf/reactome.n3

monarch/clinvar.ttl
monarch/biogrid.ttl
monarch/ctd.ttl
monarch/go.ttl
monarch/hgnc.ttl
monarch/ncbigene.ttl
monarch/omim.ttl
monarch/reactome.ttl
```

**Comment by stevencox** [comment]
* Developed provenance infrastructure proposal for translator.
* Discussed webservice design with clinical and exposure teams
* Continuing to identify data model.
* Ownership of all exposure API material transferred to the exposures team.
* Beginning to focus on a Green specific API for the hackathon.

**Comment by stevencox** [comment]
- Took next incremental step in developing **data model**
  - Developed detailed design of interaction with the clinical service
  - Published exposure service externally
  - Began integrating client for the exposure service
  - Investigated bridging Monarch, chem2bio2rdf, CTD expo, etc 
- Developed alpha of devops **provisioning** for new cluster infrastructure.
- Used LD-VOWL to visualize our semantic data store

**Comment by stevencox** [comment]
- From the NCATS architecture call:
  - We need issues to track registration of Exposures and Clinical as smartAPIs
  - Architecture would like information on HUSH+
- Developed initial interface for integrating hackathon notebooks with Green data lake:
  - Exposures via generated Python client
  - MedBioChem via SPARQL
- Power outage: need to restore SSD array, Blazegraph and med-biochem data
- Investigating integrating Census ACS data as a socioenvironmental data service
- Lost confidence in CTD environmental exposures as a source for our PM2.5 related queries  
- Made progress with installation of new cluster
- Tried various Jupyter plugins for Spark

**Comment by KCB13** [comment]
For Hackathon guidance from NCATS, please go to the NCATS Biomedical Data Translator google drive folder > Architecture/Hackathon > May 9-11 Hackathon Guidance. This document seems to be updated every couple of days.

**Comment by stevencox** [comment]
## Exploring Our Medical-BioChemical (MBC) Semantic Web.

In addition to the three service endpoints we'll be providing at the hackathon, we'll come with a library of basic operations implemented to allow others to be productive quickly. These are effectively subqueries of Green team's competency queries.

### 1. Imported Chemical Toxicogenomic Database (CTD) data into RDF format

CTD downloads come in several formats, but, so far, not in RDF. We need to get CTD into some format we can query readily as part of a Translator query. ​The import of the CTD data was facilitated with a rough and ready Spark/Zeppelin script. It loads the CSV download from CTD, reformats key fields into an RDF Notation 3 (N3) format, and creates a simple namespace. The resulting file is then imported into our Blazegraph Medical BioChemical data set. We use the bio2rdf.org namespace to integrate with chem2bio2rdf, since that's (part of) the IRI format it uses for MeSH identifiers. We ultimately expect this to be represented very differently using something like the Monarch/ENVO ontology but this integrates it for our short term purposes.

### Questions
​D​o we have lingering concerns about the applicability of this data to our competency questions?

### RDF Generation in Spark:
```
​      ​%pyspark
      #http://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000591
      ctd_namespace = "http://identifiers.org/envo/ctd"
      def write_rdf (index, row):
          result = [
                  "<{0}/observation/{1}> <{0}/resource/stressoragentname> \"{2}\" .".format (ctd_namespace, index, row.stressoragentname),
                  "<{0}/observation/{1}> <{0}/resource/stressoragentid> <http://bio2rdf.org/mesh:{2}> .".format (ctd_namespace, index, row.stressoragentid)
                  ]
          if row.diseasename is not None:
              result.append ("<{0}/observation/{1}> <{0}/resource/diseasename> \"{2}\" .".format (ctd_namespace, index, row.diseasename))
          if row.diseaseid is not None:
              result.append ("<{0}/observation/{1}> <{0}/resource/diseaseid> <http://bio2rdf.org/mesh:{2}> .".format (ctd_namespace, index, row.diseaseid))
          if row.reference is not None:
              result.append ("<{0}/observation/{1}> <{0}/resource/reference> \"{2}\" .".format (ctd_namespace, index, row.reference))
          return result
      ctd_exposure_events.rdd. \
          zipWithIndex(). \
          flatMap (lambda r : write_rdf (index=r[1], row=r[0])). \
          coalesce (1). \
          saveAsTextFile ("/projects/stars/translator/var/ctd/ctd_environmental_exposures.rdf")
```
## 2. Environmental Exposure Query
Once we've imported those components of the CTD environmental exposures data set, we can now search for PM2.5 related medical conditions in a manner that's somewhat integrated with our chem2bio2rdf data model.
​​​
### Questions
Presumably, we want to broaden diseaseID values to include some broader phenotype like cough, croup, etc, yes?

### ​Query:
```
prefix envo:  <http://identifiers.org/envo/ctd/resource/>
prefix mesh:  <http://bio2rdf.org/mesh:>
select ?exposure ?stressorAgentID ?stressorAgentName ?diseaseID where {

  values ( ?stressorAgentID ?stressorAgentName ?diseaseID ) {
    ( mesh:D052638 "Particulate Matter" mesh:D001249 )
  }

  ?exposure envo:stressoragentid     ?stressorAgentID ;
            envo:diseaseid           ?diseaseID ;
            envo:stressoragentname   ?stressorAgentName .
}
```

## 3. Genes and Pathways Query:
We need to be able to navigate the graph of medical and biochemical knowledge from a medical condition or medication to  a set of genes and biological pathways associated with those genes.

### Questions
- ​Are we using the right gene ids - SwissProtID?
- This searches for genes and pathways associated with croup, asthma, and cough. What else do we include?
- Is there a better pathway database than KEGG?
- What information about the pathway is important to return?
​### Query
```
prefix kegg:      <http://chem2bio2rdf.org/kegg/resource/>
prefix pharmgkb:  <http://chem2bio2rdf.org/pharmgkb/resource/>
prefix drugbank:  <http://chem2bio2rdf.org/drugbank/resource/>
prefix pubchem:   <http://chem2bio2rdf.org/pubchem/resource/>
prefix ctd:       <http://chem2bio2rdf.org/ctd/resource/>
prefix omim:      <http://chem2bio2rdf.org/omim/resource/>
prefix mesh:      <http://bio2rdf.org/mesh:>

select ?diseaseID ?drugGenericName ?swissProtID ?uniprotGeneID ?geneBankID ?pathwayName ?keggPath where {

    ?keggPath    kegg:protein                ?swissProtID ;
                 kegg:Pathway_name           ?pathwayName .
    ?keggInter   kegg:cid                    ?pubchemCID .

    ?dbInter     drugbank:GeneBank_ID        ?geneBankID ;
                 drugbank:SwissProt_ID       ?swissProtID ;
                 drugbank:gene               ?uniprotGeneID ;
                 drugbank:Name               ?name ;
                 drugbank:DBID               ?drugID .
  
    ?drugID      drugbank:CID                ?pubchemCID ;
                 drugbank:Generic_Name       ?drugGenericName .

    ?ctd_disease ctd:diseaseid               ?diseaseID ;
                 ctd:cid                     ?pubchemCID .
 
    values ( ?diseaseID ) {
            ( mesh:d001249 ) ( mesh:d003371 ) ( mesh:d001249 )
    }
}​​
ORDER BY ?diseaseName
```
It's not clear that MeSH IDs have a unified normal form, even within chem2bio2rdf. This may need to be solved to integrate results from these queris, as well as Monarch with chem2bio2rdf.

**Comment by stevencox** [comment]
## 1. Exposure Triggers via CTD Chemical-Gene Data

Last week, we revisited item 2 above about finding genes and pathways associated with PM2.5 based on the CTD environmental exposure data. We determined that it would be preferable to use the broader concept of particulate matter (because that's what the data has, currently) in CTDs gene-chemical data mapping. So the query has been re-written like this:

```
prefix chemgene: <http://chem2bio2rdf.org/ctd/resource/ctd_chem_gene/>
prefix mesh:     <http://bio2rdf.org/mesh:>
prefix ctd:      <http://chem2bio2rdf.org/ctd/resource/>
prefix kegg:     <http://chem2bio2rdf.org/kegg/resource/>
prefix pharmgkb: <http://chem2bio2rdf.org/pharmgkb/resource/>

select ?chemical ?gene ?kegg_pathway ?pathway_name ?pathway_id where {

   values ( ?chemical ) {
      $chemicals
   }

   ?chemgene      ctd:chemicalid       ?chemical ;
                  ctd:interaction      ?interaction ;
                  ctd:interactiontypes ?interaction_types;
                  ctd:gene             ?gene .
 
   ?pharmgkb_gene pharmgkb:Symbol      ?gene ;
                  pharmgkb:UniProt_Id  ?uniprotid .
   
   ?kegg_pathway  kegg:protein         ?uniprotid ;
                  kegg:Pathway_name    ?pathway_name ;
                  kegg:description     ?pathway_descr ;
                  kegg:pathwayid       ?pathway_id ;
                  kegg:ID              ?pathway_nid .
}
```

That lets us pass in the MeSH ID for particulate matter, for example, to get a list of genes and pathways affected. 

## 2. Tangerine Notebooks

The above changes, exposed through the Python interface we're putting together for the Hackathon, lets us do this:

```
exposures = translator.\
    get_medbiochem().\
    get_exposure_conditions (chemicals = [ 'D052638' ])
pprint.pprint (exposures[:5], indent=2)
```
Which produces output like this: 

```
[ { 'chemical': 'http://bio2rdf.org/mesh:D052638',
    'gene': 'http://chem2bio2rdf.org/uniprot/resource/gene/MAPK1',
    'human': True,
    'pathID': 'hsa04664',
    'pathName': 'path:hsa04664 Fc epsilon RI signaling pathway - Homo sapiens '
                '(human)',
    'pathway': 'http://chem2bio2rdf.org/kegg/resource/kegg_pathway/hsa04664'},
  { 'chemical': 'http://bio2rdf.org/mesh:D052638',
    'gene': 'http://chem2bio2rdf.org/uniprot/resource/gene/MAPK1',
    'human': True,
    'pathID': 'hsa04664',
    'pathName': 'path:hsa04664 Fc epsilon RI signaling pathway - Homo sapiens '
                '(human)',
    'pathway': 'http://chem2bio2rdf.org/kegg/resource/kegg_pathway/hsa04664'},
  { 'chemical': 'http://bio2rdf.org/mesh:D052638',
    'gene': 'http://chem2bio2rdf.org/uniprot/resource/gene/MAPK1',
    'human': True,
    'pathID': 'hsa04664',
    'pathName': 'path:hsa04664 Fc epsilon RI signaling pathway - Homo sapiens '
                '(human)',
    'pathway': 'http://chem2bio2rdf.org/kegg/resource/kegg_pathway/hsa04664'},
  { 'chemical': 'http://bio2rdf.org/mesh:D052638',
    'gene': 'http://chem2bio2rdf.org/uniprot/resource/gene/MAPK1',
    'human': True,
    'pathID': 'hsa04666',
    'pathName': 'path:hsa04666 Fc gamma R-mediated phagocytosis - Homo sapiens '
                '(human)',
    'pathway': 'http://chem2bio2rdf.org/kegg/resource/kegg_pathway/hsa04666'},
  { 'chemical': 'http://bio2rdf.org/mesh:D052638',
    'gene': 'http://chem2bio2rdf.org/uniprot/resource/gene/MAPK1',
    'human': True,
    'pathID': 'hsa04666',
    'pathName': 'path:hsa04666 Fc gamma R-mediated phagocytosis - Homo sapiens '
                '(human)',
    'pathway': 'http://chem2bio2rdf.org/kegg/resource/kegg_pathway/hsa04666'}]
```

**Comment by stevencox** [comment]
### 1. Tangerine Notebooks

We've created notebooks for the first four of Green team's competency questions. They're checked in to the Tangerine [cq-notebooks](https://github.com/NCATS-Tangerine/cq-notebooks) repository. 

### 2. Greentranslator

The Python interface to Green services works for endpoints for the Exposure and BioChem services. This week we hope begin adding support for clincial.

### 3. Provenance Integrated

Given generally positive feedback about the provenance approach, it's been integrated in to the GreenTranslator. This means that after executing a sequence of queries to multiple data sources, we can print a structured record of the algorithms, parameters, execution times, and data sources consulted in producing the analytic result. The model uses the W3C PROV standard, supports visualization, and the PROV-JSON specification.

### 4. JupyterHub on translator.ncats.io + Clinical

The plan is to install JupyterHub on translator.ncats.io. We hope to get greentranslator installed in that environment to be prepared for the hackathon. The major missing link right now is connectivity to the clinical API (integration with greentranslator Python API and enabling access to the service for the translator machine's IP address)
