### ISSUE TITLE
M1A: Expand efforts to engage with other Translator teams, in addition to Orange Team (e.g., Red Team)

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/greendatatranslator#31]
Issues relating to this milestone: #4, #13, #14, #15, #16, #17, #18, #21, #22, #23, #24, #26, #27, #29, #30, #57, #63, #64, #66, #67, #68, #69, #70, #71, #72, #73, #74, #84

**Comment by karafecho** [comment]
Refer to #26. Refer to #27. Refer to #29. Refer to #30.

**Comment by karafecho** [comment]
March 23, 2017: Dave, Emily, and Kara met with Melissa, Chris Chute, Maureen, and Tricia to discuss additional areas for collaboration. Will move forward with development of a 'synthetic' asthma data set (OT); will provide CDWH counts of patients with Fanconi anemia (GT).

**Comment by karafecho** [comment]
Refer to #85.
