### ISSUE TITLE
M1B: SG: Execute and evaluate initial demonstration use case on asthma

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/greendatatranslator#32]
Issues relating to this milestone: #4, #16, #17, #21, #22, #23, #24, #28, #29, #30, #51, #52, #56,  #57, #58, #59, #63, #64, #65, #70, #75, #76, #77, #78, #79

**Comment by karafecho** [comment]
Refer to #30.

**Comment by karafecho** [comment]
Refer to #29. Refer to #20. Refer to #22.

**Comment by karafecho** [comment]
Refer to #26. Refer to #27. Refer to #29. Refer to #30.

**Comment by karafecho** [comment]
Refer to #28. Refer to #29. Refer to #30.
