### ISSUE TITLE
Develop Clinical SmartAPI

### ISSUE THREAD

**Issue by rayi113** [ResearchSoftwareInstitute/greendatatranslator#4]
- 80 percent complete

**Comment by rayi113** [comment]
Need clinical query service

**Comment by KCB13** [comment]
Updated to 80% complete to match with Milestone m2b.27 in [GreenTeamMilestonesTasksCommunications_0to6Months_03.02.17](https://docs.google.com/spreadsheets/d/1IG1PrzneSUBFFMZV4hlxREY0hQM7cODgt4fj5aYAl3o/edit#gid=1731054240)
