### ISSUE TITLE
Develop Middleware for SmartAPI

### ISSUE THREAD

**Issue by rayi113** [ResearchSoftwareInstitute/greendatatranslator#5]
- 50 percent complete

**Comment by balhoff** [comment]
Plan is to create a minimal Python Flask web app to provide the REST API and pass queries to the actual data services. Similar to https://github.com/biolink/biolink-api

**Comment by balhoff** [comment]
Begun here: https://github.com/balhoff/exposures-api

**Comment by KCB13** [comment]
Updated to 50% complete to match with Milestone m2b.13 in [GreenTeamMilestonesTasksCommunications_0to6Months_03.02.17](https://docs.google.com/spreadsheets/d/1IG1PrzneSUBFFMZV4hlxREY0hQM7cODgt4fj5aYAl3o/edit#gid=1731054240)

**Comment by KCB13** [comment]
Closed; refer to issue #6
