### ISSUE TITLE
IRB Modification

### ISSUE THREAD

**Issue by karafecho** [ResearchSoftwareInstitute/greendatatranslator#51]
Jim Balhoff and Kara Fecho to complete required forms and training for non-UNC personnel.

**Comment by karafecho** [comment]
Kara has completed all required forms, training, and requests for clarification.

**Comment by balhoff** [comment]
I've completed all forms and am presently progressing through CITI training.

**Comment by karafecho** [comment]
I was unable to retrieve my CITI certificate because my account is linked to a dead email. Thus, I am repeating the training.

**Comment by balhoff** [comment]
I've completed CITI training, so there should be nothing remaining now from me.

**Comment by empfff** [comment]
IRB has been resubmitted, waiting for Stan to sign off. IRB will likely reach out to Jim and Kara to ask them to fill out a reliance agreement. May no longer apply to Jim once he's at RENCI.

**Comment by karafecho** [comment]
Kara was removed from the IRB protocol; Jim was reclassified as a RENCI/UNC employee. New modifications are pending approval.

**Comment by karafecho** [comment]
IRB received approval on April 25, 2017.

**Comment by KCB13** [comment]
@empfff to get @mjstealey on IRB. See https://docs.google.com/document/d/12UOTgKsErMF_l0M3xyx8XG4An1u2sNDHt5QbtA8JQb0/edit# for October task list item 7.

**Comment by empfff** [comment]
I can't put @mjstealey on the IRB yet, because our prior modification to add Kimberly has not yet been approved by the IRB. By the time that happens, Stan will likely be out on vacation, and so will be unable to certify any new modifications. So, I don't think this will get done for a few weeks.

**Comment by StanAhalt** [comment]
I can certify from afar, I think.  VPN


--
Stanley Ahalt, Ph.D.
Director, Renaissance Computing Institute
Professor, Department of Computer Science, UNC-CH
Assoc. Director of Biomedical Informatics Service, NC TraCS

For appointments, contact Asia Mieczkowska jomiecz@renci.org<mailto:jomiecz@renci.org>, ph# 919.445.9641
