### ISSUE TITLE
Query Biopsy: High-level Query to Data Sources/Elements to Technical Approach

### ISSUE THREAD

**Issue by karafecho** [ResearchSoftwareInstitute/greendatatranslator#52]
This issue involves the dissection of the demonstration use case queries from high-level text to requisite data sources/elements to technical approach for execution in GitHub.

**Comment by karafecho** [comment]
Free-text dissection of high-level queries to high-level technical approach.

Visual representation of queries: high-level to data sources to data elements and linkages.

**Comment by karafecho** [comment]
Steve, Jim, and Kara to begin populating the Orange Team's 'Tangerine' GitHub site (https://github.com/NCATS-Tangerine/cq-notebooks/) with Green Team folders for each of our queries. Specifically, Kara to create readme files from the queries in the GreenTeamQueriesToTechnicalApproach spreadsheet; Steve and Jim to create Jupyter notebooks.

**Comment by karafecho** [comment]
Green Team folders were created on Tangerine GitHub site. Readme files were added for all five queries; Jupyter notebooks were added for queries 1, 2, 3, and 4. Notebooks remain in development.

**Comment by karafecho** [comment]
Proposed definitions of phenotype and endotype and documentation related to GT's thoughts regarding endotyping distributed to OT, Endotype Process Interest Group, and NCATS.

**Comment by karafecho** [comment]
See #75

**Comment by karafecho** [comment]
Promising preliminary results obtained for CQ1(a) using real patient data integrated at patient level with PM2.5 exposures data. Preliminary results were presented at the hackathon.

**Comment by stevencox** [comment]
This activity has morphed in a variety of ways. We have a Query and Interface themed Translator call. We have deep dive biopsies on the Reasoner and Inference thread. Let's discuss disposition of this issue.
@karafecho @cbizon
