### ISSUE TITLE
Develop Exposure API Service

### ISSUE THREAD

**Issue by rayi113** [ResearchSoftwareInstitute/greendatatranslator#6]
- 90 percent complete

API: [exposures.renci.org](https://exposures.renci.org/v1/ui/#/default)

---

- When can we expect more/better/larger sample CMAQ data?

- TODO: revamp layout of exposures documentation at: [exposures api repo](https://github.com/mjstealey/datatranslator)
  - based on mtg notes with Kara from 4/20

---

Environmental Exposures API
- [x] swagger definition at [swaggerhub](https://app.swaggerhub.com/apis/mjstealey/environmental_exposures_api/1.0.0)
    - [x] request @balhoff review for sanity
- [x] service implementation at [exposures.renci.org](https://exposures.renci.org/v1/ui/#/default)
    - implementation continues to evolve

Backend development at [mjstealey/datatranslator](https://github.com/mjstealey/datatranslator)
- [x] implement server in python (using connexion(flask)/gevent)
- Work items
    - [x] exposures endpoint for discovery: [bdtgis.renci.org:9090/v1/exposures](http://bdtgis.renci.org:9090/v1/exposures)
    - [x] query parameter validation code for scores / values (branch: [expsosures-stub-out](https://github.com/mjstealey/datatranslator/tree/expsosures-stub-out))
    - [x] return valid JSON as stubs from CMAQ sample for pm25 ~~and o3~~
      - [bdtgis.renci.org:9090](http://bdtgis.renci.org:9090/v1/ui/#/default) - virtualenv - sorting out proxy pass to https issue
      - [bdtapps.renci.org:9090](http://bdtapps.renci.org:9090/v1/ui/#/default) - docker isolated instance
- [x] update swagger hub definition (and link to Github) to point at [exposures.renci.org](https://exposures.renci.org/v1/ui/#/default)

Query hardening
- [x] implement valid pm25 queries for values / scores
- [x] implement valid o3 queries for values / scores

**Comment by balhoff** [comment]
@rayi113 does this ticket constitute the Python web API? Or is that instead #5?

**Comment by cpschmitt** [comment]
?They are dups I believe

________________________________

**Comment by cpschmitt** [comment]
Well, not that I'm looking closer, we should consider this the backend service that the Python web API will call.

Lisa, this service will need to handle the requests coming from Python web API  (issue #5) for the environmental exposure API.  Focus for now should be on pm2.5 and ozone.  I'd start with getExposureValue then later we can do the getExposureScores

**Comment by lstillwe** [comment]
After discussion with Jim at ideathon (3/3/17), we determined that this task should really be a library that provides code to query green team postgresql/postgis database for exposure data.

**Comment by balhoff** [comment]
@mjstealey swagger API is looking good - one question. It looks you returning an array of separate exposures? I don't have expertise in the exposure calculations at all, but I had gotten the impression that the return was a composite score of the person's overall exposure. What do you think?

**Comment by mjstealey** [comment]
> I had gotten the impression that the return was a composite score of the person's overall exposure

@balhoff - Based on the **temporal_resolution** parameter there looked to be the desire to get both **hour** and **day** results. And since **exposure_point** could be more than one location with weekday / hour modifiers (i.e. `35.123233,-79.548765,Sa0813;35.720278,-79.176389,other`) we opted to default to a structure that allowed for multiple values or scores to be returned without them being ambiguous. Our first thought was an array of exposures, which is currently implemented, but are willing to change this to be something else if it makes more sense.

Example: A query like this
```
curl -X GET --header 'Accept: application/json' 'http://bdtgis.renci.org:9090/v1/exposures/pm25/values?start_date=2017-03-25&end_date=2017-03-25&exposure_point=35.123233%2C-79.548765%2CSa0813%3B35.720278%2C-79.176389%2Cother&temporal_resolution=day&statistical_type=max'
```

Might return something like this
```json
[
  {
    "end_time": "2017-03-25 07:00:00",
    "exposure_type": "pm25",
    "latitude": "35.720278",
    "longitude": "-79.176389",
    "start_time": "2017-03-25 00:00:00",
    "units": "ugm3",
    "value": "28.452"
  },
  {
    "end_time": "2017-03-25 13:00:00",
    "exposure_type": "pm25",
    "latitude": "35.123233",
    "longitude": "-79.548765",
    "start_time": "2017-03-25 08:00:00",
    "units": "ugm3",
    "value": "10.231"
  },
  {
    "end_time": "2017-03-25 23:00:00",
    "exposure_type": "pm25",
    "latitude": "35.720278",
    "longitude": "-79.176389",
    "start_time": "2017-03-25 14:00:00",
    "units": "ugm3",
    "value": "28.452"
  }
]
```

**Comment by lstillwe** [comment]
This is done
