### ISSUE TITLE
Confirm HuSH+ data is ok to transfer via ITS secure FTP server

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/greendatatranslator#68]
@karafecho Kara to confirm with @empfff Emily. Aiming to confirm by Tuesday, April 25. 

@arunacs pointed out this “Using ITS Research Computing’s Secure FTP Server” link that may be useful in transferring HUSH+ data from secure locations on UNC campus to the Europa Bldg:

[UNC ITS Secure FTP Server info](http://help.unc.edu/help/using-its-research-computings-secure-ftp-server/)

Refer to issue #67, once confirmed data can be transferred.

**Comment by rayi113** [comment]
@arunacs pointed out this “Using ITS Research Computing’s Secure FTP Server” link along that may be useful in transferring HUSH+ data from secure locations on UNC campus to the Europa Bldg:

https://help.unc.edu/help/using-its-research-computings-secure-ftp-server/
