### ISSUE TITLE
Load PM 2.5 Data

### ISSUE THREAD

**Issue by rayi113** [ResearchSoftwareInstitute/greendatatranslator#7]
- 100 percent complete

**Comment by cpschmitt** [comment]
This issue is for loading ozone data to allow for getting raw pm2.5 measurements through the exposure API.

**Comment by rayi113** [comment]
@jameschump to send @lstillwe OpenAQ scraping scripts

**Comment by lstillwe** [comment]
Using scripts from James (which use OpenAQ api to download data from OpenAQ site). Data there only from 3/2016 to current.

**Comment by lstillwe** [comment]
James delivered scripts, and I have modified to retrieve pm25 or o3 data and save all retrieved fields to DB loadable CSV file
