### ISSUE TITLE
Support Data-driven Endotype Discovery

### ISSUE THREAD

**Issue by stevencox** [ResearchSoftwareInstitute/greendatatranslator#75]
Work with @jameschump and @krobasky to get clinical data, characterize it, and cluster into endotypes.
Activities include:
  * Get clinical data
  * Organize records as useful entities (observations to patients, for example)
  * Develop feature vectors for resulting records
  * Cluster the results
  * Combine data with environmental
  * Try to demonstrate Query 1 with the combined dataset
  * Present those findings at the Sept NCATS VIP mtg

**Comment by karafecho** [comment]
- Meetings with Kimberly, Hao, Steve, and Kara to agree on plan and approach for endotype service
- Locked down requirements for hackathon MVP on Friday, 9/22/17: https://docs.google.com/document/d/1gtkYf6ITfexxEQj9WYPW8iqskT-tZh84LnhtLTmboAA/edit#
- Engaged Hong to develop endotype API

**Comment by hyi** [comment]
@KCB13 Do we want to use this issue to keep track of progress on endotype API development work or create a new issue for that?

**Comment by karafecho** [comment]
@hyi I'd probably create a new issue and perhaps cross-reference the two issues.

**Comment by hyi** [comment]
@karafecho Sounds good. Thanks.

**Comment by stevencox** [comment]
Currently supporting this work primarily by working with CDW on Security for Tweetsie #90

**Comment by stevencox** [comment]
Remaining work here happening on #90. Closing this.
