### ISSUE TITLE
Fix exposures data

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/greendatatranslator#83]
See https://docs.google.com/document/d/12UOTgKsErMF_l0M3xyx8XG4An1u2sNDHt5QbtA8JQb0/edit# for Endotyping task list item 1.

**Comment by stevencox** [comment]
Hi @lstillwe, what's the status on this? Can it be closed? 

@karafecho

**Comment by lstillwe** [comment]
Yes
