### ISSUE TITLE
Refactor algorithms to find CMAQ exposures via lat lon

### ISSUE THREAD

**Issue by lstillwe** [ResearchSoftwareInstitute/greendatatranslator#87]
The exposures API needs to be refactored to find the CMAQ exposure data, when provided with a lat lon. Exposures will be found via a column, row lookup, using info from the CMAQ NetCDF files.

**Comment by arunacs** [comment]
CMAQ data for 2011 @ 12-km resolution for the entire U.S. processed for CSV format. Will share with team after QA.

**Comment by lstillwe** [comment]
Completion status: 90%

**Comment by stevencox** [comment]
Hi @lstillwe - can this be closed?

**Comment by lstillwe** [comment]
Yes - I will close.
