### ISSUE TITLE
NCATS Follow-up Requests and Related Activities

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/greendatatranslator#88]
This issue is to track activities relevant to NCATS' requests. Including

- February 2017 Request
  - For the 6 months report
- May Hackathon Follow up
  - For a post-Hackathon presentation 
- July 2017 Request
  - To present the current progress of Data Translator to NCATS' council

**Comment by karafecho** [comment]
NCATS Translator Reasoner Proposal submitted and awarded $50K for travel to January 2018 hackathon (official NoA pending).

**Comment by karafecho** [comment]
Visit with Chris Austin on January 26, 2018. Presentation archived in Dropbox/Slides/GreenGammaTeamPresentation_ChrisAustin_v3 REVISED 01.26.18.

**Comment by stevencox** [comment]
Complete.
