### ISSUE TITLE
Develop and publish endotype API

### ISSUE THREAD

**Issue by karafecho** [ResearchSoftwareInstitute/greendatatranslator#94]
This issue involves the development and publication of a new endotype API.

**Comment by karafecho** [comment]
Refer to #75.

**Comment by karafecho** [comment]
Initial [endotype API and associated documentation](https://endotypes.renci.org/v1/ui/#!/default/endotypes_post) was published pre-hackathon.

**Comment by xu-hao** [comment]
Finished writing the postgres code for sparse array representation in the postgres database and csv file for the wide format table converted from HuSH+ long format table for the LOINC and MDCTN code.

Working on writing python code for importing the wide format into python sparse array data structure.

**Comment by xu-hao** [comment]
Postgres script to export to sparse.
Python script to import sparse into panda.

**Comment by stevencox** [comment]
Completed. Approach supplanted by [clinical feature vectors](https://github.com/ResearchSoftwareInstitute/greendatatranslator/issues/108).

@karafecho
