### ISSUE TITLE
Rewrite script to convert CMAQ netCDF exposures data to extract all variables

### ISSUE THREAD

**Issue by lstillwe** [ResearchSoftwareInstitute/greendatatranslator#97]
Rewrite script to convert CMAQ netCDF exposures data to extract all variables available from 2010 and 2011 and directly create Postgres DB table

**Comment by lstillwe** [comment]
Related to this: https://github.com/RENCI/cmaq-exposure-api/issues/12

**Comment by mjstealey** [comment]
Data is presently being ingested into database at cmaq-dev.edc.renci.org

2010:
- 112 rows x 148 cols x 24 hrs x 365 days = **145,205,760** rows of data
- 72 variables: var + 6 aggregate = 504 columns of data per row

2011:
- 299 rows x 459 cols x 24 hrs x 365 = **1,202,231,160** rows of data
- 122 variables: var + 6 aggregates = 854 columns of data per row
- 70 variables overlap with 2010

**Comment by lstillwe** [comment]
This is completed
