### ISSUE TITLE
Construction Manual Writing/Editing

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/greendatatranslator#99]
This is to keep track of who from the green team is working on what section of the construction manual. 

Assignees, please comment with what sections of the construction manual that you are working on.

**Comment by hyi** [comment]
I am working on user interface section of the construction manual and have contributed my writing to the user interface section initial draft.

**Comment by balhoff** [comment]
I am contributing edits to the "system architecture" section and the "data and standards" section.

**Comment by stevencox** [comment]
Editing "system architecture".

**Comment by karafecho** [comment]
I am drafting the Preface, Vision section, and Concluding Remarks. I'm also serving as editor-in-chief, so to speak. For full plan for the Construction Manual, including editor assignments, please see this [README file](https://drive.google.com/open?id=1XmCq_oI8t9rbRZakoI4BFEwpdWs8fBT8wUJZ2e_6f6Y).

**Comment by karafecho** [comment]
Kara locked document for editing on Friday, December 1 at 5:05 pm EST.

**Comment by karafecho** [comment]
V2 of full manual was distributed on 1/2/18. Comments and feedback solicited and received before, during, and after hackathon. V5 FINAL was distributed on 2/1/18. Subsequent feedback from Paul Clemmons incorporated into V6 FINAL FINAL on 2/5/18. Subsequent feedback from NCATS and Maureen Hoatlin incorporated into V7 FINAL FINAL FINAL on 2/9/18. Call scheduled with Julie McMurry and NCATS on 2/13/18 to discuss modifications to Figure 1.

**Comment by stevencox** [comment]
@karafecho may we close this issue and start a new one for future work on the construction manual?

**Comment by karafecho** [comment]
Yes.
